services:
  shopware:
    extra_hosts:
      - ${GALLY_SERVER_NAME:-gally.localhost}:host-gateway
    environment:
      - APP_DEBUG=0
      - XDEBUG_ENABLED=1
      - XDEBUG_REMOTE_HOST=172.17.0.1
      - XDEBUG_SERVER_NAME=${SERVER_NAME}
      - PHP_IDE_CONFIG=serverName=${SERVER_NAME}
