services:
  shopware:
    ports: !override
      - "8082:80"
      - "3308:3306"
      - "44343:443"
    environment:
      - XDEBUG_ENABLED=1
      - XDEBUG_REMOTE_HOST=172.17.0.1

networks:
  default:
    name: 'connectors-proxy'
    external: true

