# config/packages/messenger.yaml
framework:
    messenger:
        default_bus: messenger.bus.default
        failure_transport: failed
        transports:
            async:
                dsn: 'doctrine://default'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
            failed:
                dsn: 'doctrine://default?queue_name=failed'
